### ISSUE TITLE
exit status

### ISSUE THREAD

**Issue by dicktyr** [jepler/cropgui#11]
it would be useful if cropgui returned a non-zero exit status in cases where it terminates without doing any cropping

**Comment by za3k** [comment]
What's the use-case?

I would find some kind of indicator of whether it cropped the file useful, but I don't think exit status with no special flags passed is appropriate--that should be for errors. Also, cropgui can accept multiple command-line arguments and crop each, if you're not aware.
Maybe outputting a list of cropped files to stdout would be nice, because then I wouldn't have to reverse-engineer the naming convention in my shell scripts.

**Comment by dicktyr** [comment]
> What's the use-case?

more efficient scripting

> I don't think exit status with no special flags passed is appropriate--that should be for errors

fair enough
but grep and others use exit status as I suggest
(i.e. not strictly for errors but also for command failure)

```
% echo abc | grep x
% echo $?
1
```
