### ISSUE TITLE
GTK+ version confused by EXIF rotation

### ISSUE THREAD

**Issue by logological** [jepler/cropgui#26]
When the GTK+ version of cropgui displays images, it automatically rotates them in accordance with their EXIF rotation data.  However, the interactive cropping tool seems to interpret the image's dimensions as if it were unrotated.  It prevents the user from expanding or moving the cropping area outside the unrotated dimensions.

The Tkinter version does not have this problem because it does not do autorotation.

**Comment by jepler** [comment]
I agree, there's something going odd with exif-rotated jpegs.  bisect tells me
~~~~
# good: [cf0b6574c7719338d120b172d5c303c5314c0547] note that we've moved to github
git bisect good cf0b6574c7719338d120b172d5c303c5314c0547
# bad: [d0f6d9955761a88569756885130f685a7287ec68] packaging: depend on the package with jpegtran, exifautotran
git bisect bad d0f6d9955761a88569756885130f685a7287ec68
# bad: [823b3fd6f616cd133f23579d26031a08c3cc5275] Merge branch 'master' of github.com:reubot/cropgui into reubot-master
git bisect bad 823b3fd6f616cd133f23579d26031a08c3cc5275
# bad: [2babc8d9587ef4fd3f2ce81fd59267dd94ea56e5] new computation of scale
git bisect bad 2babc8d9587ef4fd3f2ce81fd59267dd94ea56e5
# good: [dea4c6a49939c753dccc62df789753c7ae551dd8] prototypical implementation for fixed size cropping
git bisect good dea4c6a49939c753dccc62df789753c7ae551dd8
# good: [3409320dced30f37474a94a1040055cf7ea43119] set_stdsize bugfix keeping aspect ratio
git bisect good 3409320dced30f37474a94a1040055cf7ea43119
# bad: [1d1fb3e6a2c778f127b94791b67a21b4b31f3986] adapted cropgtk to image coordinates
git bisect bad 1d1fb3e6a2c778f127b94791b67a21b4b31f3986
# skip: [ef5ba8feb7a5ed9ae0fdbbf10fd36c52fc6abf35] changed w,h,left,right,top,bottom to image coordinates (prevent rounding errors)
git bisect skip ef5ba8feb7a5ed9ae0fdbbf10fd36c52fc6abf35
# only skipped commits left to test
# possible first bad commit: [1d1fb3e6a2c778f127b94791b67a21b4b31f3986] adapted cropgtk to image coordinates
# possible first bad commit: [ef5ba8feb7a5ed9ae0fdbbf10fd36c52fc6abf35] changed w,h,left,right,top,bottom to image coordinates (prevent rounding errors)
# skip: [ef5ba8feb7a5ed9ae0fdbbf10fd36c52fc6abf35] changed w,h,left,right,top,bottom to image coordinates (prevent rounding errors)
~~~~

**Comment by jepler** [comment]
@onno74 can you offer us any insight?

**Comment by onno74** [comment]
Sorry for introducing the bug. I changed cropgui_common (commit ef5ba) to work on image coordinates instead of screen coordinates to prevent rounding errors. As tkinter is the frontend of my choice, I accidently completely forgot about cropgtk. Actually, it did not work at all after my changes.

Later, @reubot fixed most of it, commit aff64. Apparently he forgot about the exif rotation.
I have never seen the cropgtk source. Moreover, cropgtk does not run at all on my system:
  File "./cropgtk.py", line 173, in do_render
    pixbuf = gtk.gdk.pixbuf_new_from_data(rendered.tostring(),
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 695, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.
So I would prefer if someone else could fix this in cropgtk.

**Comment by jepler** [comment]
oh yes, that is breakage from the folks in the "pillow" project.  I thought I'd accepted a pull-request that rooted all those out, but either I failed to do so or one was missed.

**Comment by jepler** [comment]
Indeed, this (tobytes vs to string) was *also* broken at the ref I cited above, fixed in parallel at b664d1fefd71.

**Comment by aleksejrs** [comment]
Thanks for getting this fixed (why didn't I report it?).

There is some strangeness with height now: for some image rations, it uses the whole screen height, so that the bottom part of the image is hidden behind (at least) the panel.

**Comment by onno74** [comment]
Thank you, Jeff, for fixing the rotation bug. I was a bit late with yesterday's comment. Also, after fetching from the jepler-repository, I can confirm that the tostring-bug is fixed.

About the panel: How would you suggest to handle that? Every windows manager has its own panel height, and some panels are hidden (which is a workaround for the problem). What do you mean by "it becomes OK after cropping"?

**Comment by aleksejrs** [comment]
> How would you suggest to handle that? Every windows manager has its own panel height, and some panels are hidden (which is a workaround for the problem).

I maximize most of my windows, so they don't go under the panel. But CropGUI cannot be maximized: nothing happens when I click the square or press the hotkey.

> What do you mean by "it becomes OK after cropping"?

I crop the sides of a 3000×4000 image, then open the 1864×4000 result to crop the part I couldn't see, and it is displayed smaller, so everything fits.
