### ISSUE TITLE
Option to deactivate lossy edge transformation

### ISSUE THREAD

**Issue by blun** [jepler/cropgui#6]
While lossy edge transformation is a really useful feature, I'd like an option to deactivate it and instead restrain cropping to 8/16 pixel blocks also for the right-hand and bottom sides.

**Comment by isync** [comment]
+1 second this feature request

**Comment by dreamlayers** [comment]
@blun, what makes you think cropgui does lossy edge transformation? It uses `jpegtran` and its [man page](https://linux.die.net/man/1/jpegtran) says:

> the upper left corner of the selected region must fall on an iMCU boundary. If it doesn't, then it is silently moved up and/or left to the nearest iMCU boundary (the lower right corner is unchanged.)

It's all lossless, just the top left position is inexact.

**Comment by Ndolam** [comment]
> @blun, what makes you think cropgui does lossy edge transformation? It uses `jpegtran` and its [man page](https://linux.die.net/man/1/jpegtran) says:
> 
> > the upper left corner of the selected region must fall on an iMCU boundary. If it doesn't, then it is silently moved up and/or left to the nearest iMCU boundary (the lower right corner is unchanged.)
> 
> It's all lossless, just the top left position is inexact.

(As I understand it) If the new picture size is not a multiple of the MCU, the rightmost and/or bottom edges of the picture will not be complete blocks, and thus they must be decoded and dealt with specially.  You could argue about the "losslessness" of this, but in any case some people might prefer to not have such partial blocks.  One reason is if the image is later rotated or mirrored, either the partial blocks have to stay at the bottom or right (which is wrong), or the whole image must be decoded and reencoded, causing more loss.

I also second this feature request.

**Comment by Ndolam** [comment]
Notwithstanding the fact that there was no "help wanted" tag on this issue, I decided to implement it.

Jepler: what is the easiest way for me (speaking as a git-noncompliant person) to get the changes to you?
If all else fails, I'll put the diffs in a comment here.

**Comment by akostadinov** [comment]
@Ndolam , I guess easiest is to create a pull request to this repo.

**Comment by Ndolam** [comment]
No doubt easiest for someone who knows how to do that (note my comment about being git-noncompliant!).  I guess I have another project to work on.  But it would also be nice to hear from jeplin, just to know that a PR is his preferred way.

I also added in ***rudimentary*** support for zooming in.  If there is someone here that (a) wants zoom functionality, and (b) is good with GTK, then I'd be happy to talk with them about doing zoom in a non-rudimentary way.

**Comment by akostadinov** [comment]
@Ndolam , if you can program, then git would be easy for you to get. Unfortunately I can't find the guide that helped me grasp it as it was long ago. But I think official git tutorial should be alright. Basically once you understand every file is a hash and every branch is a reference to a set of hashes, and how to access remote repos and branches, you should be comfortable with what is going on. I mean going just a little bit in the low level will make you feel comfortable as staying at the very high level makes everything feel like magic and appearing to work strangely.

But anyway, the simplest way you could do (this is for one off, not good for frequent use), you can 
* fork the repo from github ui
* open your fork and click "code", then use https or ssh URL to clone locally
* make your changes
* git add path1/file1 .. pathN/fileN
* git commit -m "deactivate lossy transformation or whatever description"
* git push origin HEAD
* create a pull request from github UI

For more frequent use, you have to add original repo as a remote, `pull` remote changes, use the `hub` cli tool to create pull requests on the cli, perhaps setup commit signing.

**Comment by jepler** [comment]
making a pull request is the best way to propose changes to cropgui. Here's another doc that goes fairly step by step about using git and github to create your first pull request: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github/create-your-pull-request

I'm glad you're excited about improving cropgui. just a note: it's easier to accept a pull request when it does just one thing (avoiding partial blocks) rather than two things (avoiding partial blocks PLUS implementing image zooming) so my request would be to start with a pull request that just does whichever one you want to start with, then doing a 2nd PR later.

Thanks!

**Comment by Ndolam** [comment]
As you see, I sent a pull request.  If you squint just right, it only does one thing.  If you peek closer, you will see that I fixed what I assumed was a cropping bug (i.e., with keyboard commands you could set the crop box to include space outside the image).  And while I was there I fixed a couple of typos (ICMU instead of iMCU).
I'll send you a zoom pull request if/when this one gets through your review process.

**Comment by jepler** [comment]
Now fixed in the main branch thanks to @Ndolam's work.
