### ISSUE TITLE
jpegtran errors with "Invalid crop request"

### ISSUE THREAD

**Issue by jens-arnold** [jepler/cropgui#92]
Both when using the file browser to select images to crop and when passing (relative or absolute) paths from the command line, cropgui shows the image and you can select the crop area, but when trying to crop, it doesn't work. It just prints a message to the console that the file wasn't found.
The only working method (and only if just the folder names contain space but not the filename) is to `cd` into the directory containing the files, and then calling cropgui with a relative path (i.e. just the filename).

**Comment by howff** [comment]
The code has been written to crop filenames with spaces
https://github.com/jepler/cropgui/blob/9dbf930d0c24bba760223cb63f35390781a17f2a/cropgui_common.py#L171

I can see this might fail if `subprocess.call()` defaulted to using `shell=True`, but the default is `shell=False` so it should work. Could you try changing it to `subprocess.call(command, shell=False)` and see if that improves it?

**Comment by klartext** [comment]
Correction: I tested it with cropgtk.py

**Comment by fenugrec** [comment]
I seem to be having that problem , but... not all the time ? I was able to crop 1 out of 6 files in a certain folder. Others failed with "Error: file not found"... and the path contains a space for all of those.

**Comment by fenugrec** [comment]
```
nice jpegtran -copy all -crop 2639fx2076f+704+320 -outfile /home/....../IMG_20220717_133230913-crop.jpg /home/..../IMG_20220717_133230913.jpg
Invalid crop request
rotation 1 -> 1
image_rotation None
Error: File not found - /home/q/ddocs/mans/PSU/chargeur mastercrap 12v/IMG_20220717_133230913-crop.jpg
```

Ah, but what does "Invalid crop request" mean ? and does it have anything to do with the "File not found" error ?

**Comment by howff** [comment]
I suspect it is failing to crop - do the "f" characters in the dimension string have something to do with it?

**Comment by jepler** [comment]
I was also noticing the "f" characters. On Debian this is supported in jpegtran from libjpeg-turbo-progs and was apparently added circa 2013 (in 1.2.90 (1.3 beta1)) and is noted as being ported from "jpeg-8d". The submitter of that feature also had it on their system, but maybe it's not everywhere.

If you're comfortable using the command-line, can you try "jpegtran -version"? mine prints `libjpeg-turbo version 2.0.6 (build 20210314)`.  Manually doing a crop at the commandline using the "f" syntax could help determine if this is unsupported in your version of jpegtran.

So at first we have jpegtran probably failing with "invalid crop request", possibly due to the unsupported "f" syntax; then, exiftool fails. That's the kind of message I get when it does:
```
$ exiftool -overwrite_original -Orientation=1 nope.jpg
Error: File not found - nope.jpg
    0 image files updated
    1 files weren't updated due to errors
```
since a failed jpegtran wouldn't create an output file.

I'm not thrilled about the idea of sniffing jpegtran versions ...

**Comment by fenugrec** [comment]
thanks.

>  "jpegtran -version"

`libjpeg-turbo version 2.1.4 (build 20220816`

either the 'f'  is indigestible or the crop dims are larger than the image ? (thinking of #100  here )

**Comment by jepler** [comment]
Can you attach a specific image that fails, along with the exact jpegtran command line show in the terminal window?

What OS are you using?

**Comment by fenugrec** [comment]
Hi,
I think since #104 was merged ( I don't remember seeing the `Invalid crop request` in a long time), I don't recall having further issues. While I didn't open this ticket, as far as I'm concerned it's "fixed until further notice"

**Comment by jepler** [comment]
Thanks, closing issue.
